declare global {
  const PRELOADER_WINDOW_WEBPACK_ENTRY: string
  const CONSOLE_WINDOW_WEBPACK_ENTRY: string
  const MAIN_WINDOW_WEBPACK_ENTRY: string
  const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string
}
